AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main infrastructure stack that references nested stacks'

Parameters:
  EnvironmentName:
    Type: String
    Default: 'dev'
  
  VpcCIDR:
    Type: String
    Default: '10.0.0.0/16'

  BucketName:
    Type: String
    Description: "The name of the S3 bucket where the templates are stored"

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/network.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: !Ref VpcCIDR

  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/storage.yaml'

  SecretStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/secret.yaml'

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [NetworkStack, StorageStack]
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/lambda.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        LambdaSecurityGroup: !GetAtt NetworkStack.Outputs.LambdaSecurityGroup
        PrivateSubnetId1: !GetAtt NetworkStack.Outputs.PrivateSubnetId1
        PrivateSubnetId2: !GetAtt NetworkStack.Outputs.PrivateSubnetId2
        BucketName: !GetAtt StorageStack.Outputs.BucketName
        SecretArn: !GetAtt SecretStack.Outputs.SecretARN

  LoadBalancerStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [NetworkStack, LambdaStack]
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/${BucketName}/alb.yaml'
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt NetworkStack.Outputs.VpcId
        PrivateSubnetId1: !GetAtt NetworkStack.Outputs.PrivateSubnetId1
        PrivateSubnetId2: !GetAtt NetworkStack.Outputs.PrivateSubnetId2 
        LambdaFunctionArn: !GetAtt LambdaStack.Outputs.LambdaFunctionArn
        LambdaSecurityGroupId: !GetAtt LambdaStack.Outputs.LambdaSecurityGroupId
        ALBTargetGroupName: assesment
        ALBSecurityGroup: !GetAtt NetworkStack.Outputs.ALBSecurityGroupId