AWSTemplateFormatVersion: '2010-09-09'
Description: 'Assesment template for storage setup'

Parameters:
  EnvironmentName:
    Type: String
    Default: 'dev'

Resources:
  SecretManagerSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${EnvironmentName}/app-secret'
      SecretString: '{"username": "admin", "password": "supersecret"}'
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
          
Outputs:
  SecretARN:
    Description: 'ARN of the secret'
    Value: !Ref SecretManagerSecret
    Export:
      Name: !Sub '${EnvironmentName}-SecretARN'