AWSTemplateFormatVersion: '2010-09-09'
Description: 'Basic infrastructure setup for verification'

Parameters:
  EnvironmentName:
    Type: String
    Default: 'dev'
    Description: 'Environment name for resource tagging'

Resources:
  TestBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::AccountId}-${EnvironmentName}-stack-bucket'
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName

Outputs:
  BucketName:
    Description: 'Name of the created S3 bucket'
    Value: !Ref TestBucket